//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BourseWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class DB_BourseEntities : DbContext
    {
        public DB_BourseEntities()
            : base("name=DB_BourseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<spMarketValue_Result> spMarketValue()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spMarketValue_Result>("spMarketValue");
        }
    
        public virtual ObjectResult<spAvgPrice_Result> spAvgPrice()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spAvgPrice_Result>("spAvgPrice");
        }
    }
}
