//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BourseWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwBazaarPanic
    {
        public System.DateTime Date { get; set; }
        public string DatePersian { get; set; }
        public Nullable<decimal> AvgClosingPrice { get; set; }
        public Nullable<decimal> AvgVolumeWeightedPrice { get; set; }
        public Nullable<decimal> AvgClosingPricePercentDiff { get; set; }
        public Nullable<decimal> AvgVolumeWeightedPricePercentDiff { get; set; }
        public Nullable<decimal> AvgClosingPricePercentChange { get; set; }
        public Nullable<decimal> AvgVolumeWeightedPricePercentChange { get; set; }
        public Nullable<decimal> AvgVolume { get; set; }
    }
}
